backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, required: false, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Button Link", name: "button_link", widget: string},
              {label: "Button Text", name: "button_text", widget: string},
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", required: false, widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: About Entries
            name: about_entries
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
              - label: Detail 1/3
                name: detail0
                widget: text
              - label: Detail 2/3
                name: detail1
                widget: text
              - label: Detail 3/3
                name: detail2
                widget: text
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, required: false, widget: string}, {label: Description, name: description, required: false, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, required: false, widget: string}, {label: Description, name: description, required: false, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, required: false, widget: image}, {label: Alt, name: alt, required: false, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, required: false, widget: image}, {label: Alt, name: alt, required: false, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, required: false, widget: image}, {label: Alt, name: alt, required: false, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, required: false, widget: image}
      - file: "site/content/prices/_index.md"
        label: "Prices Page"
        name: "prices"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Prices
            name: prices
            widget: list
            fields:
              - {label: Heading, name: heading, required: false, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Price, name: price, required: false, widget: text}
              - {label: Image, name: imageUrl, required: false, widget: image}
          - label: Notes
            name: notes
            widget: list
            fields:
              - {label: Text, name: text, widget: text}
